### ISSUE TITLE
Navigation back to the home page

### ISSUE THREAD

**Issue by kmacedovarela** [redhat-solution-patterns/contributors-guide#2]
Problem: once in a specific pattern page, it’s not easy for the user to navigate back to the home page.
Suggested:
Make the entire title area point to the home page

![Screen Shot 2022-09-13 at 11 48 08](https://user-images.githubusercontent.com/253186/189933048-9a626512-3e06-4a2b-bb16-09224f565b7c.png)

**Comment by Pathholder1806** [comment]
Hey @kmacedovarela !
I would like to contribute to this issue.

**Comment by Pathholder1806** [comment]
Hey @kmacedovarela !
I have generated the PR. Kindly review the proposed changes and feel free to suggest any further updates if any!

**Comment by Pathholder1806** [comment]
Hey @kmacedovarela !
Any update in the issue ?

**Comment by Pathholder1806** [comment]
Hey @kmacedovarela 
Is anyone having a look on this issue ?

**Comment by kmacedovarela** [comment]
Hi @Pathholder1806 thank you so much for your contribution. I plan to review and approve by the end of this week. 

Thanks for your patience!

**Comment by Pathholder1806** [comment]
Thanks for reverting back @kmacedovarela

**Comment by Pathholder1806** [comment]
Hey @kmacedovarela any update ?

**Comment by jayachristina** [comment]
fixed
