### ISSUE TITLE
Add a "Try It" tab on the content overview

### ISSUE THREAD

**Issue by kmacedovarela** [redhat-solution-patterns/contributors-guide#3]
from:
![Screen Shot 2022-09-13 at 11 49 07](https://user-images.githubusercontent.com/253186/189933274-f6215982-a72e-4e5a-938a-79ef4fbc3ff7.png)

to:
![Screen Shot 2022-09-13 at 11 49 15](https://user-images.githubusercontent.com/253186/189933309-057c1c59-5de1-42b0-955b-8cb31eaa861d.png)

**Comment by jayachristina** [comment]
new Developer resources tab is being added now for each SP
