### ISSUE TITLE
Add technology links pointing to RHD pages

### ISSUE THREAD

**Issue by kmacedovarela** [redhat-solution-patterns/contributors-guide#4]
Under Technology Stack update URLs to point to Red Hat Developer spaces. For example: Quarkus: https://developers.redhat.com/products/quarkus/overview

 
![Screen Shot 2022-09-13 at 11 50 13](https://user-images.githubusercontent.com/253186/189933572-a656ccfb-f112-4b9a-81a4-8756066c49be.png)

**Comment by jayachristina** [comment]
This is done in each sp
